toolbar:
  - insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image
  - image | link
plugins:
  - image
  - link
  - advlist
  - wordcount
